-- NOTE: This file is auto generated by ./sql-generator

-- DynamicAlbumRepository.getById
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."id" = $1
  and "dynamic_albums"."deletedAt" is null

-- DynamicAlbumRepository.getOwned
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."ownerId" = $1
  and "dynamic_albums"."deletedAt" is null
order by
  "dynamic_albums"."createdAt" desc

-- DynamicAlbumRepository.getShared
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  exists (
    select
    from
      "dynamic_album_shares" as "shares"
    where
      "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      and "shares"."userId" = $1
  )
  and "dynamic_albums"."deletedAt" is null
order by
  "dynamic_albums"."createdAt" desc

-- DynamicAlbumRepository.getMetadataForIds
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."id" = $1
  and "dynamic_albums"."deletedAt" is null

-- DynamicAlbumRepository.getAssets
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."id" = $1
  and "dynamic_albums"."deletedAt" is null

-- DynamicAlbumRepository.getAssetCount
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."id" = $1
  and "dynamic_albums"."deletedAt" is null

-- DynamicAlbumRepository.getFirstAssetForThumbnail
select
  "dynamic_albums".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "users"
        where
          "users"."id" = "dynamic_albums"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shares"."role",
          "shares"."createdAt",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  "users"
                where
                  "users"."id" = "shares"."userId"
              ) as obj
          ) as "user"
        from
          "dynamic_album_shares" as "shares"
        where
          "shares"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "sharedUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "dynamic_album_filters"
        where
          "dynamic_album_filters"."dynamicAlbumId" = "dynamic_albums"."id"
      ) as agg
  ) as "filters"
from
  "dynamic_albums"
where
  "dynamic_albums"."id" = $1
  and "dynamic_albums"."deletedAt" is null

-- DynamicAlbumRepository.delete
delete from "dynamic_albums"
where
  "id" = $1

-- DynamicAlbumRepository.softDelete
update "dynamic_albums"
set
  "deletedAt" = now()
where
  "id" = $1

-- DynamicAlbumRepository.restore
update "dynamic_albums"
set
  "deletedAt" = $1
where
  "id" = $2
